# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
all: &all
  postmark: <%= ENV["RHIZOME_POSTMARK"] %>

development:
  <<: *all
  secret_key_base: 53fb6064ac7c7921ab5e6460b150cba92e98a5ee6749416343ca86959fcc878fe01489e57a229aa1ae7960beb9564d48568b74ce1e5732d6c5478ee9e8a0932d
  postmark: <%= ENV["RHIZOME_POSTMARK"] %>
  facebook_key: <%= ENV["OAUTH_RAILS_FB_KEY"] %>
  facebook_secret: <%= ENV["OAUTH_RAILS_FB_SECRET"] %>
  twitter_key: <%= ENV["OAUTH_RAILS_TW_KEY"] %>
  twitter_secret: <%= ENV["OAUTH_RAILS_TW_SECRET"] %>
  linkedin_key: <%= ENV["OAUTH_RAILS_LI_KEY"] %>
  linkedin_secret: <%= ENV["OAUTH_RAILS_LI_SECRET"] %>
  github_key: <%= ENV["OAUTH_RAILS_GH_KEY"] %>
  github_secret: <%= ENV["OAUTH_RAILS_GH_SECRET"] %>
  dropbox_key: <%= ENV["OAUTH_RAILS_DB_KEY"] %>
  dropbox_secret: <%= ENV["OAUTH_RAILS_DB_SECRET"] %>


test:
  <<: *all
  secret_key_base: a9ed60d003ba1b8004ac9b1a25501cdd88d218151a0135755120233460dd2f3a7a3b76e75913f1d9e7b75f59c993d910e210f4de6a15733c7ffded216a148377

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *all
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
